CREATE TABLE IF NOT EXISTS characters (
    character_id serial PRIMARY KEY,
    name VARCHAR (255),
    gender VARCHAR (20) UNIQUE,
    identity VARCHAR(255),
    theme VARCHAR(255),
    origin VARCHAR(255),
    level INT,
    fpoints INT,
    initiative INT,
    hp INT,
    mp INT,
    ip INT,
    dexterity INT,
    insight INT,
    might INT,
    willpower INT,
    slow BOOLEAN,
    dazed BOOLEAN,
    weak BOOLEAN,
    shaken BOOLEAN,
    enraged BOOLEAN,
    poisoned BOOLEAN,
    zenit INT
);